### ISSUE TITLE
Wrong color in beggining

### ISSUE THREAD

**Issue by KeMoonoDev** [ComputerElite/RedBar#1]
I have set under 50% and over 50% both to completely white and whenever I start a new song and the bar is half full the bar is always a bit red and whenever I hit a block it fixes itself. Fade between 15% and 95% is off.

**Comment by ComputerElite** [comment]
That was a typo on my side which set the color on start to 40% instead of 50%. Is now fixed in the latest release https://github.com/ComputerElite/RedBar/releases/latest Thanks for reporting
