### ISSUE TITLE
disable itself on bmbf when i turn on custom menu

### ISSUE THREAD

**Issue by Junglefresh07** [ComputerElite/RedBar#3]

**Comment by Junglefresh07** [comment]
every time i turn on custom menu it disables itself

**Comment by ComputerElite** [comment]
Which version of beat saber do you run?

**Comment by kodenamekrak** [comment]
Could you please elaborate on what you mean by custom menu?

**Comment by Junglefresh07** [comment]
im on 1.25.1 and there is a mod called custom menu

**Comment by Junglefresh07** [comment]
but it turns off when custom menu is enabled

**Comment by kodenamekrak** [comment]
Hi, after looking into this i have discovered it is an issue with custom main menu, not RedBar, i have messaged the creator of the mod to let them know of their mistake

**Comment by ComputerElite** [comment]
Mind sharing what you discovered?
